os: windows
language: node_js
node_js:
  - node
env:
  global:
    - RELEASE_NAME=PinUpBrowser
before_script:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install zip ; fi
script:
  - npm run build
deploy:
  provider: releases
  api_key:
    secure: C3MfrCcgmSuc530TewWVYt3Ot+M2zX+DfM+4JIklsqoX9xqNOfVSQW1fNujKD42ltj6NPRpJf348UNKuDI+K4n9+0nMEGzpmnpGY/WGjaFVujbC7pdTsj4lILnVxJvIByCF+2QR6q5zsvvL68zFq/NkHIXwmrFG8fT0qlZk1XjRR1lfJunLh+WoSvIub9VDAMAtCpblKgmWNVt7L/MmLUMh/DEoV+RVGESsDZS7ZhDLY1F043EUf0PDNGdygg1i27tMPm4xPN3NdEM95+wXI5qxiLbTeb1Y//vBOZU6HzkiqheQaxf8AoK/ldJ3ELyIXqet7xdNbf3a4x7DlipeUME6fbCGNDPdOYhYsyLudZC152o6oarUBlGtdVs7uL470XRGWyzpB9PG3Mr78AN7Q2nZBVLA56PgxM5DsYz1Jmlzm3X68sG15amjs9kWY3xIO9ucgMyWAYcGFv+Ig+HNK9bvhB8fWJydDyB9kxuf8U982twRMU9jBkisoWZ+RRszEricdiXpoUjh9HhgQeb4vGL1Ku/i7s+M+oYFWQcji4tE6M6vFpjdekNBmfF9c5edSYmmsEjW6WfabhTIFn5hYbTJnYur3AocGFecJPqzAzU2TXV7UBvH1JJimC9bI5VWGKszBrDVLKx7RM+aUBqDAzMsrJ3XBvltJrMB7Ls/6P/I=
  file: $RELEASE_NAME.zip
  on:
    tags: true
  skip_cleanup: true
  draft: true
