pupServer:
  url: http://localhost
  db:
    path: C:\PinUpSystem\PUPDatabase.db
    filter: ifnull(GameTheme, 1) <> 'Adult' and (emuid = 1 or emuid = 4)

httpServer:
  port: 3000
  logFormat: dev
  logLevel: debug

options:
  filters:
    category: true
    theme: true
    type: true
    decade: true
    emulator: true
    manufacturer: true
    favorites: true
    playlist: true
  game:
    info: true
    help: true
    playfield: true
    backglass: true
    allMedia: true

media:
  useThumbs: true
  cacheInMinutes: 20
  playfieldRotation: true
