pupServer:
  url: http://localhost
  db:
    path: C:\PinUpSystem\PUPDatabase.db
    filter: ifnull(GameTheme, 1) <> 'Adult'

httpServer:
  port: 3000
  logFormat: dev #combined, common, dev, short, tiny  see https://github.com/expressjs/morgan
  logLevel: info #info, error

options:
  filters:
    category: true
    theme: true
    type: true
    decade: true
    emulator: true
    manufacturer: true
    favorites: true
  game:
    info: true
    help: true
    playfield: true

media:
  useThumbs: true
  cacheInMinutes: 20
  playfieldRotation: true
