pupServer:
  url: http://localhost
  mediaDirRoot: /PinUpSystem/POPMedia
  db:
    path: /PinUpSystem/PUPDatabase.db
    filter: ifnull(GameTheme, 1) <> 'Adult'
	
httpServer:
  port: 3000

options:
  filters:
    category: true
    theme: true
    type: true
    decade: true
    emulator: true
    manufacturer: false
  game:
    info: true
    help: true
    playfield: true



